[theme]
base = "dark"
primaryColor = "#34d5c8"
backgroundColor = "#08272e"
secondaryBackgroundColor = "#0b2d34"
textColor = "#cbe8e4"
font = "monospace"

[server]
headless = true

[browser]
gatherUsageStats = false
